/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#614000",
        "primary-fixed-dim": "#b5c6f1",
        secondary: "#4e6073",
        "surface-variant": "#e4e2de",
        "primary-fixed": "#d8e2ff",
        tertiary: "#251600",
        "inverse-primary": "#b5c6f1",
        "on-tertiary-container": "#c58a18",
        "on-secondary": "#ffffff",
        "primary-container": "#1b2d4f",
        "on-primary-fixed-variant": "#35466a",
        "inverse-surface": "#30312e",
        "secondary-fixed": "#d1e4fb",
        surface: "#fbf9f5",
        "surface-bright": "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-tint": "#4d5e83",
        primary: "#031839",
        "on-primary": "#ffffff",
        "on-background": "#1b1c1a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#061b3c",
        "outline-variant": "#c5c6cf",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container-high": "#eae8e4",
        background: "#fbf9f5",
        "tertiary-fixed": "#ffddaf",
        "tertiary-fixed-dim": "#fdba49",
        "tertiary-container": "#402900",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#281800",
        "secondary-fixed-dim": "#b5c8df",
        "secondary-container": "#cfe2f9",
        "on-secondary-container": "#526478",
        "on-secondary-fixed": "#091d2e",
        "on-secondary-fixed-variant": "#36485b",
        "on-error": "#ffffff",
        outline: "#75777f",
        "on-error-container": "#93000a",
        "surface-container": "#f0eeea",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#44474e",
        "on-primary-container": "#8495bd",
        "inverse-on-surface": "#f2f0ec",
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        serif: ['Noto Serif', 'serif'],
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      }
    },
  },
  darkMode: 'class',
  plugins: [],
}
